### ISSUE TITLE
No dist directory

### ISSUE THREAD

**Issue by Florian-Mahlberg** [jherr/vue-music-notation#1]
Hey, I'd like to write some music but when I run it (npm run dev) I get an error:

`[vite] Internal server error: ENOENT: no such file or directory, open 'node_modules/vue-music-notation/dist/vue-music-notation.css'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at Context.load (.\node_modules\@vitejs\plugin-vue\dist\index.cjs:2616:30)
      at Object.load (./node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35555:50)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async loadAndTransform (./node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39827:24)`
      
Any idea how I can fix this?

**Comment by katerlouis** [comment]
Also wondering
